auth:
  login-url: https://auth.jorisjonkers.dev/login

spring:
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_ADDR:http://vault:8200}
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID:}
        secret-id: ${VAULT_SECRET_ID:}
